Methodician/CoSourcery

src/app/components/account/register/register.component.html
src/app/components/account/register/register.component.scss

Fixed form placeholder and error message issues. Added styling to error message to be more inline with CoS aesthetic.

Ian register

---

src/app/services/upload.service.ts
src/app/shared/class/upload.ts

Let scope creep get me again. This is better. Only gets uploadSvc working to upload image/file to storage bucket and update object params depending on base path.

Ian upload modified

---

src/app/services/article.service.ts

Breaking change. Home displays correctly but article detail is missing all info now. Some logic commented and saved at the bottom of the page for possible later use. Other unused logic and imports removed. Next PRs will update detail and edit components to fix breaking changes.

Update article service

---

src/app/components/articles/article-detail/article-detail.component.html
src/app/components/articles/article-detail/article-detail.component.ts

Update article-detail component ts/html to reflect current changes. Detail now displays correctly. Still getting terminal error about edit component. Addressing in next PR.

Article detail first

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts

Update article-edit ts/html. No terminal errors. remove ngIf as no longer needed. 
Upload not real-time yet. Next PR will address upload and article cover image components. Added if(params) conditional, doesn't seem to have effect. Will keep for now until I get a chance to work wit it a little more. Route change as discussed coming in future PR.

Article edit first

---

src/app/components/articles/article-detail/article-detail.component.html
src/app/components/articles/article-preview-card/article-preview-card.component.ts

Address requested changes:
> 1. Wrapping div missing a space before *ngIf
**Done**
> 2. Square braces is correct and standard syntax for property binding
> e.g. src={{article.authorImageUrl}} is wrong and [src]="article.authorImageUrl" is correct.
**Thanks and Done**
> 3. "import { Subscription } from '../../../../../node_modules/rxjs';" should just be "import { Subscription } from 'rxjs';"
**This is how Angular is auto importing that's why it keeps happening. Need to remember to fix this. Done**

Article detail cleanup

---

src/app/components/account/register/register.component.ts
src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts
src/app/components/articles/article-preview-card/article-preview-card.component.html
src/app/components/articles/article-preview-card/article-preview-card.component.ts
src/app/components/articles/article-preview-list/article-preview-list.component.ts
src/app/components/general/home/home.component.html
src/app/services/upload.service.ts

Changes addressed:
> 1. The if(params) should actually be if(params['key']) - I think params will always exist. We're just checking if that particular one is on it.
**Done**
> 2. Should probably have separate create and edit functions
**Two separate functions here would gain us nothing and require a lot of potentially more confusing conditionals and duplicate HTML code. Have changed the name of edit to articleEvent for greater clarity.**
> 3.Even if not, if creation is successful you still end up calling the update function. Need to if/else it or add a return statement to cut the code off before calling the second service method.
I don’t this this is the case. 
**async edit(article) {
**_if (!article.articleId) {_**   **this conditional should catch that.**
**const creationCheck …

Ian edit cleanup

---

src/app/components/account/register/register.component.ts
src/app/components/articles/article-edit/article-edit.component.scss
src/app/components/shared/upload-form/upload-form.component.html
src/app/components/shared/upload-form/upload-form.component.scss

returned styling to edit buttons that was lost due to being (I don't know why) coming from the article-post-component.scss file. Add ngClass directive and similar styling to upload button.

Button updates

---

src/app/components/articles/article-cover-image/article-cover-image.component.html
src/app/components/articles/article-cover-image/article-cover-image.component.ts
src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts
src/app/components/shared/upload-form/upload-form.component.ts
src/app/services/article.service.ts
src/app/services/upload.service.ts

Refactored several files here to deal with errors/db clutter/UX on accidental reload of edit/create form before full article submitted.

Upload create refactor

---

src/app/components/general/home/home.component.html
src/app/components/general/home/home.component.scss

Restructured and restyled Home component. Refined responsive behavior.

Home Rebuild

---

firestore.rules
src/app/app-routing.module.ts

Adds Security rules to firestore.rules that allows reading for all, but writing only on valid login. Rules implemented on DB already.

Security Rules

---

src/app/components/articles/article-detail/article-detail.component.ts

Basic redirect when trying to access article that is not actually there. There is one broken article with an image that says "STARTUP" that I tested this on. This may not deal with every case we run into but it's a start.

Redirect error

---

src/app/components/articles/article-preview-card/article-preview-card.component.html
src/app/components/articles/article-preview-card/article-preview-card.component.scss
src/app/components/articles/article-preview-card/article-preview-card.component.ts
src/app/components/general/home/home.component.scss

Restructured and restyled ArticlePreviewCard component.

Article Preview Rebuild

---

src/app/components/articles/article-detail/article-detail.component.html
src/app/components/articles/article-detail/article-detail.component.scss

Restructured and restyled ArticleDetail component.

Article Detail Rebuild

---

src/app/components/articles/article-detail/article-detail.component.html
src/app/components/articles/article-detail/article-detail.component.scss
src/app/sass-variables-mixins/vars.scss

Removed ArticleDetail component's actions and icons from footer area and combined them with the header section to bring more attention and visibility to editing function.

Article Edit Button

---

src/app/components/account/login/login.component.html
src/app/components/account/login/login.component.scss
src/app/components/account/login/login.component.ts
src/app/components/account/register/register.component.html
src/app/components/account/register/register.component.scss
src/app/components/account/register/register.component.ts
src/styles.scss

Completed basic structural clean-up on registration form in Register component. Added styling and current-login detection for Login and Register components.

Login/Register Update

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss
src/app/components/articles/article-edit/article-edit.component.ts

Consolidated and refactored relevant code for ArticleEdit form, combining ArticleForm, ArticleCoverImage, and UploadForm sub-components within ArticleEdit. Refined form validation, functions, and styling.

ArticleEdit Rebuild

---

src/app/components/articles/article-preview-card/article-preview-card.component.html
src/app/components/articles/article-preview-card/article-preview-card.component.ts
src/app/components/articles/article-preview-list/article-preview-list.component.html
src/app/components/articles/article-preview-list/article-preview-list.component.ts
src/app/components/general/home/home.component.html
src/app/components/general/home/home.component.ts
src/app/services/article.service.ts

I refactored everything in the service to use angularfire, refactored the related components to reflect this and moved a couple functions out of the service and into the component they are being used in. let me know if there are any other changes you think should be made or if you want something done differently.

Article service

---

functions/src/index.ts
src/app/components/articles/article-preview-card/article-preview-card.component.ts
src/app/components/general/home/home.component.ts
src/app/services/article.service.ts
src/app/shared/class/article-info.ts

refactors to pull article previews from firestore instead of full articles. Also updates the firebase createPreviewObject function (I was unable to deploy this function) to make id field articleId instead

refactors article service and related components

---

src/app/components/general/top-nav/top-nav.component.html
src/app/components/general/top-nav/top-nav.component.scss
src/app/components/general/top-nav/top-nav.component.ts
src/app/sass-variables-mixins/buttons.scss

Replaced TopNav button styles with globally set styles. Added responsive mobile menu.

Navbar Update

---

src/app/components/articles/article-edit/article-edit.component.scss
src/app/sass-variables-mixins/buttons.scss

Fixed positioning of ArticleEdit body placeholder to prevent text overflow in mobile views.

New Article Fix

---

src/app/components/articles/article-preview-card/article-preview-card.component.html
src/app/components/articles/article-preview-card/article-preview-card.component.scss
src/app/components/articles/article-preview-card/article-preview-card.component.ts
src/app/sass-variables-mixins/buttons.scss

Added tooltips and authentication checks for bookmarking feature in ArticlePreviewCard.

PreviewCard Update

---

src/app/components/articles/article-edit/article-edit.component.ts
src/app/sass-variables-mixins/ckeditor.scss

Implement CKEditor media embed with pointer event fix to allow clickable media.

CKEditor Media Embed

---

src/app/sass-variables-mixins/ckeditor.scss

Updated CKEditor styles to hide UI handles for tables when editor is disabled. Enabled horizontal scrollbars for individual tables.

CKEditor Table Fix

---

database.rules.json
src/app/components/general/home/home.component.html

Created rules for firebase database. I also quickly fixed a minor bug in the home component. The search results button somehow lost the class that styled it properly.

Comment rules

---

src/app/components/account/profile/profile.component.html
src/app/components/account/profile/profile.component.scss
src/app/components/general/unauthorized/unauthorized.component.html
src/app/components/general/unauthorized/unauthorized.component.scss

Added styles for Unauthorized component and set profileForm to readonly when logging out from Profile view.

UnAuth Update

---

src/app/app.module.ts
src/app/components/account/login/login.component.html
src/app/components/account/login/login.component.scss
src/app/components/account/login/login.component.ts
src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts
src/app/components/articles/article-preview-card/article-preview-card.component.ts
src/app/components/comments/comment-list/comment-list.component.html
src/app/components/comments/comment-list/comment-list.component.ts
src/app/components/modals/login-dialog/login-dialog.component.html
src/app/components/modals/login-dialog/login-dialog.component.scss
src/app/components/modals/login-dialog/login-dialog.component.spec.ts
src/app/components/modals/login-dialog/login-dialog.component.ts

Created LoginDialog modal and implemented modal in place of all authCheck() internal alerts.

Login Modal

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss
src/app/components/articles/article-edit/article-edit.component.ts

Fixed unwanted toggling of ArticleEdit body. Added header section and tweaked header input styles.

ArticleEdit Update

---

src/app/components/articles/article-preview-card/article-preview-card.component.ts

Fixed initial login bug where bookmarking feature is broken until page reload.

Bookmark Login Fix

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss
src/app/components/articles/article-edit/article-edit.component.ts

Added a utilities bar in ArticleEdit to track stats (number of comments, edits, and tags) and allow bookmarking articles from the full article view.

ArticleEdit Utils

---

src/app/components/general/top-nav/top-nav.component.html
src/app/components/modals/login-dialog/login-dialog.component.scss

Fixed broken login and logout functions in TopNav mobile menu. Tweaked LoginDialog modal width for better rendering on mobile screens.

Mobile Login Fix

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss

Added responsive styles to fix ArticleEdit utility bar overflow in mobile view.

Responsive Utils Bar

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts

Reorganized ArticleEdit functions into logical groupings. Fixed false alert for unsaved changes when creating new articles. Fixed lastUpdated template render error when saving a new article.

ArticleEdit Refactor

---

src/app/components/articles/article-edit/article-edit.component.ts
src/app/components/modals/edit-timeout-dialog/edit-timeout-dialog.component.html
src/app/components/modals/edit-timeout-dialog/edit-timeout-dialog.component.scss
src/app/components/modals/edit-timeout-dialog/edit-timeout-dialog.component.ts

Refactored EditTimeoutDialog and its implementation in ArticleEdit. Added styles for EditTimeoutDialog. Fixed erroneous trigger of unsaved changes prompt when article editing session times out.

Timeout Modal Update

---

src/app/app.module.ts
src/app/components/account/register/register.component.ts
src/app/components/articles/article-edit/article-edit.component.ts
src/app/components/modals/message-dialog/message-dialog.component.html
src/app/components/modals/message-dialog/message-dialog.component.scss
src/app/components/modals/message-dialog/message-dialog.component.spec.ts
src/app/components/modals/message-dialog/message-dialog.component.ts

Added generic message modal to replace all alert boxes.

Message Modal

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss
src/app/sass-variables-mixins/buttons.scss
src/styles.scss

Moved ArticleEdit save button to a fixed position.

Article Save Button

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts
src/app/services/article.service.ts

Re-implemented date display for new article creation using a static placeholder timestamp.

Timestamp Placeholder

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss
src/app/components/articles/article-edit/article-edit.component.ts

Redesigned float behavior for ArticleEdit save button to conform with horizontal column of toggle buttons. Floating is also restricted to the length of the form.

Save Button Reposition

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss

Added animated flag to indicate unsaved changes in ArticleEdit.

Unsaved Flag

---

src/app/app.module.ts
src/app/components/account/profile-view/profile-view.component.html
src/app/components/account/profile-view/profile-view.component.scss
src/app/components/account/profile-view/profile-view.component.spec.ts
src/app/components/account/profile-view/profile-view.component.ts
src/app/components/account/profile/profile.component.html
src/app/components/account/profile/profile.component.scss
src/app/components/account/profile/profile.component.ts
src/app/components/general/top-nav/top-nav.component.html
src/app/services/user.service.ts

Created new profile-view component. Also added another update button to the top of the profile-form.html in the same location as the edit button in the profile-view.html.

Profile restructuring - added profile-view component.

---

package-lock.json
package.json
src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts

Would like to move some of this outside component

Re-implemented client side EXIF processing

---

package-lock.json
src/app/app-routing.module.ts
src/app/components/comments/comment/comment.component.html

Added a link to author profile on the author name on each comment. Also enabled scrollPositionRestoration in the app-routing.module to make sure that page is brought back to the top after navigating. Docs: https://angular.io/api/router/ExtraOptions (search: scrollPositionRestoration).

Linked names to profiles

---

src/app/components/articles/article-history/article-history.component.html
src/app/components/articles/article-history/article-history.component.ts

I'm making my own branch and doing a PR so you can easily see my changes and suggestions.
Also you can remove most of the comments and just search for "@MAYT" to see my notes particularly directed to you as code review.

Article history tweaks

---

src/app/components/account/profile-card/profile-card.component.html
src/app/components/account/profile-card/profile-card.component.scss
src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts
src/app/components/articles/contributors/contributors.component.html
src/app/components/articles/contributors/contributors.component.scss
src/app/components/articles/contributors/contributors.component.ts
src/app/sass-variables-mixins/mixins.scss
src/assets/images/chevron_left-24px.svg
src/assets/images/chevron_right-24px.svg

created basic horizontal scroll through contributors.

Attribution scroll

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts

scaffolded and implemented more scalable system for managing control state

Eliminated growing linst of booleans for edit controls

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts

I'm planning to keep cleaning up the ArticleEditComponent logic so that we can break the component down into more maintainable and flexible bits.

Isolated article state in preparation for further cleanup

---

src/app/admin/components/data-cleanup/data-cleanup.component.ts
src/app/admin/services/data-cleanup.service.ts
src/app/app.module.ts
src/app/components/account/profile/profile.component.ts
src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts
src/app/components/articles/article-edit/cover-image-display/cover-image-display.component.html
src/app/components/articles/article-edit/cover-image-display/cover-image-display.component.scss
src/app/components/articles/article-edit/cover-image-display/cover-image-display.component.spec.ts
src/app/components/articles/article-edit/cover-image-display/cover-image-display.component.ts
src/app/components/articles/article-edit/cover-image-edit/cover-image-edit.component.html
src/app/components/articles/article-edit/cover-image-edit/cover-image-edit.component.scss
src/app/components/articles/article-edit/cover-image-edit/cover-image-edit.component.spec.ts
src/app/components/articles/article-edit/cover-image-edit/cover-image-edit.component.ts
src/app/components/articles/article-edit/cover-image/cover-image.component.html
src/app/components/articles/article-edit/cover-image/cover-image.component.spec.ts
src/app/components/articles/article-edit/cover-image/cover-image.component.ts
src/app/shared/class/user-presence.ts
tsconfig.json

Created specialized components for article image display and file management to in continued effort to improve flexibility and maintainability of the article system.
Updated a TSConfig rule (off-branch move) and will continue to optimize linting and config standardization over time

Article image componentization

---

src/app/services/article.service.ts

Might actually want to remove it from the bookmark method...

Added flag filters to the other article preview lists

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts

This helps ensure the placeholders are visible and minimizes bug
Also happens to fix bug where tags couldn't be added until content was added.
I also edited the placeholder and eror text,

Quick fix to ensure article starts with content

---

functions/src/index.ts
src/app/components/account/profile-form/profile-form.component.html
src/app/components/account/profile-form/profile-form.component.scss
src/app/components/account/profile-view/profile-view.component.html
src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.ts
src/app/services/article.service.ts
tslint.json

Edit form now has better (and working) placeholder content.
Profile now doesn't display email address to public.

Updates to edit form and profile

---

src/app/app.module.ts
src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss
src/app/components/articles/article-edit/title/title-display/title-display.component.html
src/app/components/articles/article-edit/title/title-display/title-display.component.spec.ts
src/app/components/articles/article-edit/title/title-display/title-display.component.ts
src/app/components/articles/article-edit/title/title-edit/title-edit.component.html
src/app/components/articles/article-edit/title/title-edit/title-edit.component.spec.ts
src/app/components/articles/article-edit/title/title-edit/title-edit.component.ts
src/app/components/articles/article-edit/title/title.component.html
src/app/components/articles/article-edit/title/title.component.scss
src/app/components/articles/article-edit/title/title.component.spec.ts
src/app/components/articles/article-edit/title/title.component.ts

Into short component tree
Still more could be done, but it's another step towards maintainability

Extracted title display and edit

---

src/app/components/account/profile-card/profile-card.component.html
src/app/components/account/profile-card/profile-card.component.ts

Created because the username string truncation length of 8 was too long for the mobile version profile-card component. so now we are truncating at

now detecting window size to determine when to truncate username.

---

src/app/components/articles/article-edit/article-edit.component.html
src/app/components/articles/article-edit/article-edit.component.scss
src/app/components/articles/article-edit/cover-image-display/cover-image-display.component.ts
src/app/components/articles/article-edit/title/title.component.html
src/app/components/articles/article-edit/title/title.component.scss
src/app/components/articles/article-edit/title/title.component.ts

Also cleaned up some cover image stuff

Title controls now fully encapsulated

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/account/profile-view/profile-view.component.ts
src/app/components/articles/article/article.component.spec.ts
src/app/components/articles/article/article.component.ts
src/app/components/general/home/home.component.ts
src/app/shared/guards/unsaved-changes.guard.ts

CoSourcery articles and profiles are finally showing up in organic search results! Who knows why... our SEO is garbage. It showed stuff like this:
We'll probably still need to introduce server side rendering to get the full benefit of these changes.

Adding meta tags and title to home, profile, and article
